# Generated by Django 6.0.3 on 2026-03-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='language',
            field=models.CharField(choices=[('ja', '日本語'), ('en', '英語'), ('zh', '中国語')], default='ja', max_length=10),
        ),
    ]
